language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_script:
  - mysql -u root -e 'CREATE DATABASE labspring;'
  - mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
  - mysql -u root -e "GRANT ALL ON labspring.* TO 'sa'@'localhost';"
before_install:
  - chmod +x mvnw